# Generated by Django 6.0.6 on 2026-06-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
